---
date: 2023-06-23T03:05:18Z
tags:
- blogging in june 2023
- meta
---
= Blogging in June: Status Update II 

Blogging is great, but time is finite.

We are now a little more than two-thirds into June.
After having a very bumpy past two weeks due to hopping between school events and work, I am now working a full 40 hours a week until mid-August.
This hopping around hasn't had a great effect on my ability to write consistently.
I luckily have no shortage of ideas to write about: I have six more long-term posts at various levels of completion. 
The issue is putting time aside to work on them while posting here every day.

Another issue I've had with posting consistenly is needing to decompress after work.
I usually find that I either need to nap or go outside for a bit to fully exit "work mode."
I am aware that this process is very important to my mental health and quite nice, but it does suck up valuable hours that could be spent writing.

I've been very happy with my output as of late.
This blog has already helped me to stop procrastinating on stuff I've been meaning to do and articulate problems I've been debating with myself in my mind.
Writing does a good job of making you slow down and process what you're thinking about.

While I don't think I'll come out the other end of this month with a perfect track record, this challenge has finally forced me to build out a respectable Internet presence and further discover the joy of writing for others, even if I'm only writing for as many people as I have digits.

I think the plan for July is to have one post every Wednesday; this is for numerous reasons:

* I still want to write, but I know I don't have the fire in my heart to write on my own just yet, so I need to create a fire under my butt instead.
* Having one post a week instead of one post a day allows me to focus more on longer-form writing.
* Having posts in the middle of the week, as opposed to either end, will hopefully force me to spread out the act of reading over the week instead of crunching on the weekend.

I also want to improve the site technically and visually, but haven't found the time to do that just yet since I want to spend my precious time writing instead of coding.

See you at the end of the month for a final retrospective!
