---
date: 2023-06-02T21:45:20Z
tags:
- announcement
- meta
- blogging in june 2023
---
= Blogging in June With a Friend

To improve at writing and to finally stop procrastinating with blogging,
I have partnered with Kiera J. Reed to write a blog post every day for the month
of June.
Kiera (she/her/hers) is a great computer scientist and maker who, along with me
is a member of MIT's Class of 2027. I'm very exited to see what she writes over the
following weeks! Her blog can be found at https://kierajreed.dev/[]. I thank her
for holding me accountable in terms of wriitng every day and finally
finishing up this dang blog.

As for what you can expect from me, I have a couple of themes and ideas
I'm attempting to get to:

* programming in Python, Rust, Java, and other languages
* discussions of artificial """intelligence"""
* how I write about sex and gender
* breakdowns of cool school projects I've done
* maintaining and updating this blog
* and more!

If this goes according to plan, both Kiera and I should compulsively blog
without prompting and I will have a presentable internet presence beyond GitHub. 
Time for the Kyle Anthony Williams Computer Company to get to work!
