---
date: 2023-06-16T01:03:54Z
tags:
- personal
- blogging in june 2023
- transportation
- scooter
---
= Thoughts on Scooter Riding

I just came back from an hour-and-a-half long scooter ride; this 
post contains my thoughts on it and possible improvements.

== Why?
Why did I decide to climb through all the junk in my garage
to get to my scooter?
I wanted to go out to buy lunch, and realized I was getting
tired of most of my commute being spent on walking.
Once I got my food, I dug through the back of my garage
for a scooter I my family bought at Walmart just before the 
beginning of the COVID-19 pandemic.

== Thoughts on Riding

My scooter, even though I've bought it recently,
is definitely too small for me; my left foot takes
up more than half the base, so I let my right
dangle on the side when I'm not pushing.

Wow, do you go fast on a scooter.
A pair of legs can get you pretty far in an hour,
but I was able to go two communities over in a half-hour!
I can reasonably go visit my borough's central library
without a car ride or the bus!
It was suprising to me that with enough effort and a small
decline I was able to keep up with bike riders.
Riding is also just straight up *fun*!
Feeling the wind rush by your face and appreciating
the beautiful, diverse communities of my borough
while getting through my podcast backlog was lovely.

That isn't to say that my ride wasn't without issues.
My sccoter has no shock absorbtion and you can feel it
in your feet and especially your hands; my fingers
still sting a little.
Many roads near me don't have bike lanes, and the ones
that do reguarly have cars idling them, requiring me to
move onto the bumpy sidewalk and inconvience others.
When the bike lane is clear, I ran into no issues
with bike or motorcycle riders, but I did have a few
close calls with cars because I couldn't check my 6 to 9
without tearing my eyes away from the road.
You can ride on roads without bike lanes for the most part;
you just need to exert a lot of caution.

Finally, I need to get better at braking.
The brake on my back wheel is not strong enough to stop my
scooter; it needs encouragement from me pulling back on the
handlebars.
Breaking with your foot can work if you're desperate,
but it is not fun.

Bottom line: I'm going on scooter joyrides instead of
walks during my lunch break now. :)

== Improvements
_AKA piming my ride._

I am hesitant to buy a new scooter, even if it is a little
too small for my feet, so I plan to mod it instead.
I'm eyeing up 
https://www.amazon.com/ESI-Grips-GBK02-Chunky-Black/dp/B003FAGDNK[some foam handles]
I saw recommended in an Amazon review to reduce the
shocks that reach my hands.
I would need a lot more help figuring out if I can install
a proper shock absorber to my ride.

A
https://www.amazon.com/Hiboy-Motorcycle-Adjustable-Rotation-Compatible/dp/B0B4NCRD62[phone mount]
for my scooter would be awesome, as
it would allow me to see where I'm going with GPS without having
to stop and get off the road.
Google killed off standalone Android Auto a while back,
but the
https://support.google.com/assistant/answer/10217503[Google Assistant driving mode]
in Google Maps looks to be a decent replacement.

CGP Grey recommended in
https://www.relay.fm/cortex/141[Cortex #141]
purchasing some gloves for bike riding, and I think
I'll take him up on that seeing as I'm reguarly compelled
to screw up my body and need my hands for work.

I'm going to turn on Do Not Disturb when I go out;
getting pings distracts me from the road.
