---
date: 2023-06-11T03:09:30Z
---
= Beginning to Adult

I've done a lot of "adulting" recently that I think is interesting to note.

== Voting

I got my voting registration card from my local board of elections the other day.
I plan to vote early in local elections later this June; I'll probably vote Democrat but
I still should run a background check on everyone to assure the alignment of ideals.
It feels validating to finally have some control over how my community (even if I
won't be here frequently for much longer) and country works after feeling like an
insignificant pebble for so long.

The general election should make for some *interesting* discussions my sophomore
year of college.

== Financials

I am now the proud owner of my own checking account; it is completely untied
to my parents. I also now have a Zelle through my bank and finally got full
access back to my PayPal after having it be locked down for being a minor.
When the first deposit hits my account sometime next week from my internship,
I will for the first time have money that isn't physical that I have full control
over.
I'm planning on using my initial paycheck to buy a drawing tablet for taking notes
in the fall and geting an ergonomic keyboard for my wrists, but I may change my mind.

== Job

I currently am doing a repeat summer internship at https://streamforge.com/[Streamforge];
as the adjetive implies, I also worked there in 2022.
Doing remote work, especially in the career I love, rocks.
I appreciate that my boss just trusts me to get work done because I like doing it;
I do give him regular updates about what I'm doing, of course.
Last year, I regularly used my lunch break to go on walks and occasionally go out to eat;
I plan to do the same this year as well, as it was great for my mental health
and enabled me to listen to a lot of audiobooks and podcasts.
Finally, the ability to buy my parents a new A/C as a gift, pay the internet bill,
and purchase myself a graphics card was transformational for me.
I finally could do things for people other than myself with my keyboard and mouse. 
I definitely need to write a full post about my internship and what I've learned
as a post at some point.

== Networking

I felt for the longest time that networking was kind of icky.
The idea of a transactional relationship which LARPs as a normal one felt very off.
Now, as someone who is slowly but surely building a web of connections,
I realize that meeting people is a lot of fun, and rewarding not just for me, but for
them as well; they *want* to see me succeed!
Part of the goal of this blog is to maintain that web by sharing my thoughts with others
very asynchronously.
I hope I can continue to build a network that can I rely on and that can rely on me.

== Travel

I have been on a plane *six* times this year, all in the timespan of two months. 
During that time, I've made the realization that, as much as I love my family,
it feels good to be on my own.
Wake up and sleep on my schedule, not on theirs.
Go on long walks in unfamiliar places.
Buy a pint of ice cream and eat it on a bench with a crap plastic spoon in the cold.
Pace up and donw a room without getting in anyone's way.

== The Road to Independence

I am so close to being on my own, having the freedom to screw up and pick up the pieces
without a bunch of people looking at me funny.
If I could write this post in the comfort of a studio, I'd be quite pleased with myself.
I guess that's what I'm working towards as I walk down this road to independence.
I'm really an adult now, huh?
Guess it just hits different when you're the big one-eight.
