---
date: 2023-06-12T01:12:13Z
tags:
- productivity
- rant
---
= Deciding What to Do

There is one thing that is worse than having nothing to do: having a ton you
*can* do but then deluding yourself into doing none of it by telling yourself
that you're bored.
I find myself in that rut on the weekends, and even more so now that it's the summer,
even with my 9 to 5.
Here are some of the ways I try to keep myself together.

== Figuring Out What I *Must* Do

There are a few things I usually need to do in a day no question:
* self-care like showering, brushing my teeth, and eating
* attending scheduled events such as school, work, and meetings
* stuff with a due date of today or tomorrow

Ideally, I want to do all of these tasks or else I'll fall apart
along with the good will I've built up in my social circles.

=== On Due Dates

Due dates exist in a quantum superposition of rocking and sucking.
When they work, they are a powerful guiding force for getting
stuff done.
When they don't work, they just create stress and late-night
cram sessions.
I usually try to get far in front of deadlines for stuff like
homework so I can just not think about it anymore, but that
doesn't work too well for things with due dates that need to
be worked on regularly.

I recently watched
https://www.youtube.com/watch?v=XUZ9VATeF_4[a productivity video]
which brings up the philosophy of eating the frog: do the thing
which feels unpleasant or hard first, ideally as early as possible
or else it will turn into a roadblock for your other responsibilites.
It's a philosophy which sounds like it would work well for writing 
in June, but would be challenging to implement since I don't have
full control over my schedule due to work. I'll keep it in my head.

== Tracking TODOs

There's two ways of keeping track of things one needs to do:
writing it down or remembering it.
I suck at the latter, so I do the former a ton.

=== School and Kanban

For school, I've used a planner for quite a while.
It was a physical notebook for years, but I've now migrated to https://trello.com/[Trello]
after trying to make Google Keep work for a while and it just not working.
I'm pretty sure I'm not making full use of the power of a Kanban board,
but Trello locks a bunch of neat features like assigning due dates
to checklist items behind paywalls, so I just make it work.
Luckily, they do let you sync due Perhaps what I needdates with Google Calendar, which rocks.

For the inclined, my categories look like this:
* Homeworks: and other short-term items
* Projects
* Events: long-term items that don't fit into the project box like tests
and trips
* Tasks: small items like sending an email and future ambitions like reading an article
* Doing: marks in-progress items, usually from Homework and Tasks
* Done: items in this category are automatically archived and set to "Completeted"
* Resources: documents like "pre-exam coping strategies" and "list of college application portals" go here

=== Promising Projects and Google Keep

I use Google Keep to store theory crafting for promising projects and
occasionally short-term items.
I do wish that Google Keep supported hierarhical tagging, but oh, well.
I plan to move to Org Mode one day so that I can have more control over my notes.

=== Emailing Oneself

I use Gmail's star feature to keep track of things I want to do in my inbox.
This is especially useful if I find something interesting on a secondary computer
like my school laptop; I'll transmit the knowledge to myself with an email.
Stuff shouldn't stay in here forever though, else it gets very messy.

=== Calendaring

Google Calendar helps me keep track of meetings and stuff I should be expecting
like college results or a debit card being mailed to me.
I also have https://github.com/SuperSonicHub1?tab=repositories&q=calendar[autogenerated calendars] for staying 
on top of stuff like free games or anime coming out.

=== Wow, This Needs a Part 2

Each of these headings in a sense need their own article, and there's a bunch
of stuff which I haven't gotten to discuss, like balancing entertainment and
enrichment, using GitHub issues instead of TODO comments, RSS feeds and newsletters.

I think a deep discussion of how I do work and how I decide what to do
is crucial, especially as I transition to a very challenging college.
One thing that is clear to me is that there isn't one place for me
to decide what to do with my time; that likely feeds into my indecision
and forgetfulness.
The world everyday yells at me to finally learn Emacs and Org, and one day I
will have to listen. :/
