---
date: 2023-06-09T00:03:17Z
tags:
- meta
- programming
- blogging in june 2023
---
= Blog Updates: Syntax Highlighing and Tags

I am very behind on blog content, so let's milk the shoddy construction
of this blog for everything it's worth. :)

== Syntax Highlighting in Asciidoc Templates 

My blog has supported syntax highlighting since the beginning with
https://www.11ty.dev/docs/plugins/syntaxhighlight/[eleventy-plugin-syntaxhighlight],
but only in Markdown documents.
This made my recent blog post on link:/weblog/2022-06-08-rust-deref/[Rust zip iterators] look not so great.
By [line-through]#copy-pasting from# following
https://saneef.com/tutorials/asciidoc-syntax-highlighting/[a very helpful blog post],
that right has been wronged:

[source,python]
----
print("Hello, world!")
----

== Improved Tag Integration

I have begun to better integrate tags into the blog.
They now show up in the header of every weblog post and media consumption page;
they use similar CSS to that of my navigation bar with the addition of some
https://www.w3schools.com/howto/howto_css_badge.asp[nice badge CSS from W3Schools].
When you click on a tag, you navigate to its page, generated using 11ty's
https://www.11ty.dev/docs/pagination/[pagination functionality].
I got some extra help from 
https://www.11ty.dev/docs/quicktips/tag-pages/[their quick tip page on tag pages]
and https://github.com/11ty/eleventy-base-blog/blob/main/content/tags.njk[their `base-blog` template].
Finally, I have added a "Tags" link to the navbar, which has all the tags in one place;
this page is also based on another from https://github.com/11ty/eleventy-base-blog/blob/main/content/tags-list.njk[`base-blog`].

I intend to "backtag" all previous posts soon.
