---
date: 2023-06-04T22:37:48Z
tags:
- music
- computer science
- internet
- blogging in june 2023
---
= The Case of the Phantam Shazam Song

Some time in 2021, around November 7th, I came across
https://www.youtube.com/watch?v=VZWq73AjJd0&t=319s[an ad for alcohol on YouTube].
The advertisement, named "#TeamUpForExcellence the Film," featues at 
5 minutes, 27 seconds a song which has a striking resemblance to Kendrick Lamar's
"HUMBLE."
I, being a compulsive mashup maker, desired to make a mashup using the
song from the ad and Lamar's vocals, so I played that portion of the ad again
and piped it into Shazam, assuming that the song was licensed.
The result I got was somewhat strange.

https://www.shazam.com/track/568206741/team-up[Shazam told me] that I had heard
a song named "Team Up" by Raphael Saadiq.
After some Google searching, I later learned that Saadiq had produced the ad's soundtrack,
as explained in
https://web.archive.org/web/20211107161116/https://www.youtube.com/watch?v=AHQoe8RiO5Y[a now private behind-the-scenes video]
and https://respect-mag.com/2021/04/usher-remy-martin-raphael-saadiq-and-marci-rodgers-team-up-to-celebrate-music-and-cognac/[many a news article].
It seemed as if I had found the song, and it was not a license, but a commission.

This was all well and good, but I for the life of me could not find a copy of the song
that didn't have Usher yammering over it.
The https://www.youtube.com/watch?v=ibcTv1suoPc["""music video"""] for the song on Shazam
is a performance by two unrelated artists in some
https://rainerscafeandbar.com/[South Carolinan café], and the Shazam page is otherwise barren;
not even album art. Nothing on Google that wasn't
reporting on the ad, nothing on YouTube, nothing on Spotify, nothing on SoundCloud,
nothing on Apple Music, nothing, nothing, nothing. I became so desperate for answers
that I even wrote a plea for help on
https://www.reddit.com/r/tipofmytongue/comments/qorann/tomtsong2021_attempting_to_find_song_at_519_in/[Reddit]
and rummaged around in the DOM and network requests of the Shazam webpage to no avail.

After getting nowhere with my Reddit post, I ultimately gave up on searching for it.
Now, more than a year and a half after initially giving up, I am left with even more questions:
* Where does Shazam get its the audio for its fingerprints from? Its music metadata?
* Does Shazam hold onto the audio they use to generate fingerprints? If so, do they have a copy of the song?
* Did the alcohol company plan to release Saadiq's work but then bailed out?
* Are there more "phantom songs"—fingerprints and metadata for unreleased music—like this one just sitting in Shazam's database?

In order to get definitive to these questions, I would need to get a job at Shazam, and they are 
https://web.archive.org/web/20230604231541/https://jobs.apple.com/en-us/search?sort=relevance&search=shazam[not hiring].
Hopefully, by bringing this to the attention of more people, *some* answers can eventually be found.
I'll make sure not to get my hopes up.
